export const API_VERSION = 'v1';

export const REQUEST_ID_HEADER = 'X-Request-Id';

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  INTERNAL_SERVER_ERROR: 500,
} as const;

export const DATABASE_RETRY = {
  MAX_ATTEMPTS: 5,
  DELAY_MS: 5_000,
} as const;
